apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: channel-carrier-allchannel
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: channel-carrier-allchannel
  chart:
    git: https://github.com/vmeng/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: carrier-net
      network:
        version 2.2.0
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://192.168.249.108:8200
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel
    orderer:
      address: orderer1.supplychain-net:7050
    channeltx: |-
      CtkDChgKFggCGgYIwamFgwYiCmFsbGNoYW5uZWwSvAMKuQMKCmFsbGNoYW5uZWwSRhI0CgtBcHBsaWNhdGlvbhIlEhMKD21hbnVmYWN0dXJlck1TUBIAEg4KCmNhcnJpZXJNU1ASABoOCgpDb25zb3J0aXVtEgAa4gIStgIKC0FwcGxpY2F0aW9uEqYCCAESEwoPbWFudWZhY3R1cmVyTVNQEgASDgoKY2Fycmllck1TUBIAGiQKDENhcGFiaWxpdGllcxIUEgoKCAoEVjJfMBIAGgZBZG1pbnMiIgoGQWRtaW5zEhgSDggDEgoKBkFkbWlucxACGgZBZG1pbnMiLAoLRW5kb3JzZW1lbnQSHRITCAMSDwoLRW5kb3JzZW1lbnQQAhoGQWRtaW5zIjUKFExpZmVjeWNsZUVuZG9yc2VtZW50Eh0SEwgDEg8KC0VuZG9yc2VtZW50EAIaBkFkbWlucyIiCgdSZWFkZXJzEhcSDQgDEgkKB1JlYWRlcnMaBkFkbWlucyIiCgdXcml0ZXJzEhcSDQgDEgkKB1dyaXRlcnMaBkFkbWlucyoGQWRtaW5zGicKCkNvbnNvcnRpdW0SGRIXChVTdXBwbHlDaGFpbkNvbnNvcnRpdW0=