apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: approve-carrier-allchannel-private1
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: approve-carrier-allchannel-private1
  chart:
    git: https://github.com/vmeng/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/approve_chaincode
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://192.168.249.108:8200
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin 
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.supplychain-net:7050
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.0
      name: private
      version: 1
      commitarguments: '\"CreateAsset\",\"asset1\",\"blue\",\"5\",\"tom\",\"35\"'
      endorsementpolicies:  ''
    channel:
      name: allchannel
