apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: approve-manufacturer-allchannel-private1
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: approve-manufacturer-allchannel-private1
  chart:
    git: https://github.com/vmeng/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/approve_chaincode
  values:
    metadata:
      namespace: manufacturer-net
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.manufacturer-net:7051
      localmspid: manufacturerMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://192.168.249.108:8200
      authpath: manufacturer-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/manufacturer-net/users/admin 
      orderersecretprefix: secret/crypto/peerOrganizations/manufacturer-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.supplychain-net:7050
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.0
      name: private
      version: 1
      commitarguments: '\"CreateAsset\",\"asset_properties\" :"{\"objectType\":\"asset\",\"assetID\":\"asset1\",\"color\":\"blue\",\"size\":\"5\",\"owner\":\"tom\",\"appraisedValue\":\"35\"}"'
      endorsementpolicies:  ''
    channel:
      name: allchannel
