apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: chaincode-install-manufacturer-peer0-1
  namespace: manufacturer-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: chaincode-install-manufacturer-peer0-1
  chart:
    git: https://github.com/vmeng/blockchain-automation-framework.git
    ref: local
    path: platforms/hyperledger-fabric/charts/install_chaincode
  values:
    metadata:
      namespace: manufacturer-net
      network:
        version: 2.2.0
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.manufacturer-net:7051
      localmspid: manufacturerMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://192.168.249.108:8200
      authpath: manufacturer-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/manufacturer-net/users/admin 
      orderersecretprefix: secret/crypto/peerOrganizations/manufacturer-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretgitprivatekey: secret/credentials/manufacturer-net/git?git_password
      tls: false
    orderer:
      address: orderer1.supplychain-net:7050
    chaincode:
      builder: hyperledger/fabric-ccenv:2.2.0
      name: supply
      version: 1
      lang: golang
      maindirectory: cmd
      repository:
        hostname: "github.com"
        git_username: "vmeng"
        url: github.com/vmeng/blockchain-automation-framework.git
        branch: develop
        path: examples/supplychain-app/fabric/chaincode_rest_server/chaincode
      endorsementpolicies:  ''
