---
#######################################
# Master Playbook for the setting up and reseting the Blockchain Automation Framework DLT network
#######################################
  - hosts: all
    gather_facts: no
    no_log: True
  - import_playbook: environment-setup.yaml   # First setup environment for each organization
  - import_playbook: kubernetes-env-setup.yaml # Then deploy Flux for each organization
    when: reset is undefined or reset == 'false'
  - import_playbook: "{{ playbook_dir }}/../../hyperledger-fabric/configuration/deploy-network.yaml"
    vars:
      add_new_org: 'false'
    when: network.type == 'fabric' and (reset is undefined or reset == 'false')
  - import_playbook: "{{ playbook_dir }}/../../hyperledger-fabric/configuration/chaincode-ops.yaml"
    vars:
      add_new_org: 'false'
    when: network.type == 'fabric' and (reset is undefined or reset == 'false')
  
# Reseting the network
  
  - import_playbook: "{{ playbook_dir }}/../../hyperledger-fabric/configuration/reset-network.yaml"
    when: network.type == 'fabric' and reset is defined and reset == 'true'
  